

import { Rubik } from 'next/font/google'
import './globals.css'
//import 'bootstrap/dist/css/bootstrap.min.css';
//

const font = Rubik({ subsets: ['latin'] })

export const metadata = {
<<<<<<< HEAD
  title: 'Applicco - Criadora de Aplicativos e Softwares',
=======
  title: 'Create Next App',
>>>>>>> 2a0f35c0c13316d4fba5bff9885465c3d5b6fb1e
  description: 'Generated by create next app',
}

import Header from "../components/header"
import Footer from "../components/footer"

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={font.className}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
